name       : plasma-workspace
version    : 5.10.3
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.3/plasma-workspace-5.10.3.tar.xz : 69d7513ad0ba0acc224cd0dee824795c20e8733f52704e3cf3dca5f6ae6cdf71
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma workspace
description: |
    This package provides the interface and basic tools for the Plasma workspace.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(cln)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libqalculate)
    - pkgconfig(NetworkManager)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - iso-codes
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpackage-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - kxmlrpcclient-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
setup      : |
    %cmake -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
