name       : plasma-workspace
version    : 5.13.3
release    : 32
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.3/plasma-workspace-5.13.3.tar.xz : 442f10b8c7a514fae07c629052287d678d77c3c395aab4e74ccfe1f803e193ea
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma workspace
description: |
    This package provides the interface and basic tools for the Plasma workspace.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libqalculate)
    - pkgconfig(NetworkManager)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - iso-codes
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpackage-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
rundeps    :
    - mkfontdir
    - xdg-user-dirs
    - xdg-utils
    - xprop
    - xrdb
    - xsetroot
setup      : |
    #%patch -p1 < $pkgfiles/0001-digital-clock-enable-RFC2822-date-format.patch
    %patch -p1 < $pkgfiles/0001-Solus-tweaks-to-the-default-config.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/wayland-sessions
    %qml_cache ||:
