name       : plasma-workspace
version    : 5.11.4
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/plasma-workspace-5.11.4.tar.xz : a83bfcd753ae0e9cea2273a29f9445d178cdf288e43da4781eee7dc63e3236e2
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma workspace
description: |
    This package provides the interface and basic tools for the Plasma workspace.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libqalculate)
    - pkgconfig(NetworkManager)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - iso-codes
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpackage-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - mkfontdir
    - xprop
    - xset
setup      : |
    %patch -p1 < $pkgfiles/0001-Solus-tweaks-to-the-default-config.patch
    %cmake -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
    rm -rf $installdir/usr/share/wayland-sessions
