name       : plasma-workspace
version    : 5.20.1
release    : 79
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.1/plasma-workspace-5.20.1.1.tar.xz : 75b625dc705ec72c374dbcdb4c359ce199a33dea4af72dbf45d3830e375439a6
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma workspace
description: |
    This package provides the interface and basic tools for the Plasma workspace.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(freetype2)
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libnm)
    - pkgconfig(libqalculate)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(sm)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xcursor)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - iso-codes
    - kcmutils-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kirigami2-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpeople-devel
    - kquickcharts-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - kuserfeedback-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - prison-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - kirigami2
    - kquickcharts
    - mkfontscale
    - vala-panel-appmenu
    - xdg-user-dirs
    - xdg-utils
    - xprop
    - xrdb
    - xsetroot
    - qt5-quickcontrols2
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/wayland-sessions
    rm -rf $installdir/usr/share/doc/HTML
    %qml_cache ||:
