name       : plasma-workspace
version    : 5.11.0
release    : 6
source     :
    - https://download.kde.org/stable/plasma/5.11.0/plasma-workspace-5.11.0.tar.xz : 7c043d05a12cdb1d31b3e47bb3c8bdb312ea4889cdf5d069dcf3f18d729becd3
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma workspace
description: |
    This package provides the interface and basic tools for the Plasma workspace.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libqalculate)
    - pkgconfig(NetworkManager)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - iso-codes
    - kcmutils-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpackage-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
rundeps    :
    - mkfontdir
    - xprop
    - xset
setup      : |
    %patch -p1 < $pkgfiles/fix_user_switching.patch
    %cmake -DBUILD_TESTING=OFF .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
