name       : plasma-workspace
version    : 5.21.5
release    : 91
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.5/plasma-workspace-5.21.5.tar.xz : 9cb16ef4bca9ade0ca82d0cc539533ba9f9be47811ae13d154effc085618e90a
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  :
    - desktop.kde.core
    - ^plasma-workspace-wayland-session : desktop.kde
summary    : KDE Plasma workspace
description:
    - This package provides the interface and basic tools for the Plasma workspace.
    - ^plasma-workspace-wayland-session : Solus does not support officially Wayland, this is for testing purpose.
optimize   : lto
builddeps  :
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libnm)
    - pkgconfig(libqalculate)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(sm)
    - pkgconfig(wayland-server)
    - pkgconfig(xft)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xcursor)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - baloo-devel
    - breeze-devel
    - iso-codes
    - kcmutils-devel
    - kactivities-devel
    - kactivities-stats-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kirigami2-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpeople-devel
    - kquickcharts-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - kuserfeedback-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - libkscreen-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - prison-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - kirigami2
    - kquickcharts
    - mkfontscale
    - vala-panel-appmenu
    - xdg-user-dirs
    - xdg-utils
    - xprop
    - xrdb
    - xsetroot
    - qt5-quickcontrols2
patterns   :
    - /usr/lib64/libkdeinit5*.so
    - ^plasma-workspace-wayland-session :
        - /usr/share/wayland-sessions/plasmawayland.desktop

setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
    %qml_cache ||:
