name       : plasma-workspace
version    : 5.15.4
release    : 48
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.4/plasma-workspace-5.15.4.tar.xz : f86c2fda5b7dc2c40be1ea3c4791fef3965d2f91809700c849d30c00506753c9
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma workspace
description: |
    This package provides the interface and basic tools for the Plasma workspace.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(libKActivities)
    - pkgconfig(libqalculate)
    - pkgconfig(NetworkManager)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - iso-codes
    - kcmutils-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - prison-devel
rundeps    :
    - mkfontscale
    - vala-panel-appmenu
    - xdg-user-dirs
    - xdg-utils
    - xprop
    - xrdb
    - xsetroot
setup      : |
    %patch -p1 < $pkgfiles/0001-Solus-tweaks-to-the-default-config.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/wayland-sessions
    %qml_cache ||:
