name       : plasma-workspace
version    : 5.26.4.1
release    : 117
source     :
    - https://download.kde.org/stable/plasma/5.26.4/plasma-workspace-5.26.4.1.tar.xz : 7fcca23ff8de6f4aa2261f0180be54422f25047002b7ca6c648e7216459b80fc
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma workspace
description: This package provides the interface and basic tools for the Plasma workspace.
optimize   : lto
builddeps  :
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libnm)
    - pkgconfig(libqalculate)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libxcrypt)
    - pkgconfig(phonon4qt5)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(sm)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - baloo-devel
    - breeze-devel
    - iso-codes
    - kcmutils-devel
    - karchive-devel
    - kactivities-devel
    - kactivities-stats-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kded-devel
    - kdesu-devel
    - kdoctools-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kholidays-devel
    - kiconthemes-devel
    - kidletime-devel
    - kio-extras-devel
    - kirigami2-devel
    - kitemmodels-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpeople-devel
    - kpipewire-devel
    - kquickcharts-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - kunitconversion-devel
    - kuserfeedback-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - layer-shell-qt-devel
    - libkexiv2-devel
    - libkscreen-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - prison-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - kinit
    - kio-extras
    - kio-fuse
    - kirigami2
    - kquickcharts
    - mkfontscale
    - vala-panel-appmenu
    - xdg-user-dirs
    - xdg-utils
    - xprop
    - xrdb
    - xsetroot
    - qt5-quickcontrols2
patterns   :
    - /usr/lib64/libkdeinit5*.so
    - /usr/lib64/libkrdb.so
replaces   :
    - plasma-workspace-wayland-session
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
    %qml_cache
