name       : plasma-workspace
version    : 5.19.5
release    : 75
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.5/plasma-workspace-5.19.5.tar.xz : 490329e08e63016edd696a9132bf80b76ef51dacf53308b865d2e27b67ce8127
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KDE Plasma workspace
description: |
    This package provides the interface and basic tools for the Plasma workspace.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(Baloo)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(kscreen2)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libnm)
    - pkgconfig(libqalculate)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - extra-cmake-modules
    - iso-codes
    - kcmutils-devel
    - kdeclarative-devel
    - kded-devel
    - kdelibs4support-devel
    - kdesu-devel
    - kglobalaccel-devel
    - kholidays-devel
    - kidletime-devel
    - kirigami2-devel
    - kjsembed-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kpeople-devel
    - kquickcharts-devel
    - krunner-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - kuserfeedback-devel
    - kwallet-devel
    - kwayland-devel
    - kwin-devel
    - libksysguard-devel
    - networkmanager-qt-devel
    - prison-devel
rundeps    :
    - kirigami2
    - kquickcharts
    - mkfontscale
    - vala-panel-appmenu
    - xdg-user-dirs
    - xdg-utils
    - xprop
    - xrdb
    - xsetroot
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/wayland-sessions
    rm -rf $installdir/usr/share/doc/HTML
    %qml_cache ||:
